name: Kits
main: dev._2lstudios.kitsplugin.KitsPlugin
version: 0.0.1
author: 2LS
depend: ["InventoryAPI"]
api-version: '1.13'
commands:
  kit:
    description: Get a kit of items.
    aliases:
      - kits
  kitsetup:
    description: ""
  kitpreview:
    description: ""